myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from bankapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('input_customer/', views.input_customer, name='input_customer'),
    path('customer_list/', views.customer_list, name='customer_list'),
    path('input_transaction/', views.input_transaction, name='input_transaction'),
    path('transaction_list/', views.transaction_list, name='transaction_list'),
    path('', views.main, name='main'),
    path('point_list/', views.point_list, name='point_list'),
    path('report_buku_tabungan/', views.report_buku_tabungan, name='report_buku_tabungan'),
    path('login/', views.user_login, name='login'),
    path('register/', views.user_registration, name='register'),
    path('upload_excel/', views.upload_excel, name='upload_excel'),
]

myproject/bankapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class Customer(models.Model):
    account_id = models.IntegerField()
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Transaction(models.Model):
    account = models.ForeignKey(Customer, on_delete=models.CASCADE)
    transaction_date = models.DateTimeField()
    description = models.CharField(max_length=255)
    debit_credit_status = models.CharField(max_length=1, choices=[('D', 'Debit'), ('C', 'Credit')])
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    balance = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.debit_credit_status == 'D':
            previous_balance = Transaction.objects.filter(account=self.account, transaction_date__lt=self.transaction_date).order_by('-transaction_date').first()
            if previous_balance:
                self.balance = previous_balance.balance + self.amount
            else:
                self.balance = self.amount
        else:
            previous_balance = Transaction.objects.filter(account=self.account, transaction_date__lt=self.transaction_date).order_by('-transaction_date').first()
            if previous_balance:
                self.balance = previous_balance.balance - self.amount
            else:
                self.balance = -self.amount

        super(Transaction, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.account.name} - {self.description}"


class Point(models.Model):
    account = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total_point = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.account.name} - Point: {self.total_point}"

class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, unique= True)
    password = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=17)
    email = models.EmailField(unique= True)
    address = models.CharField(max_length=255)
    profile_photo = models.ImageField(upload_to='images/')
    is_active = models.BooleanField(default=True)
    agency = models.CharField(max_length=255)
    USERNAME_FIELD = 'username'

    def __str__(self) -> str:
        return self.username
    
class CustomerVico(models.Model):
    customer_id = models.AutoField(primary_key=True)
    VICID = models.CharField(max_length=8)
    ACCTNO = models.CharField(max_length=10)
    NO_IDEN = models.CharField(max_length=16)
    NAMA_NASABAH = models.CharField(max_length=50)

class Transaksi(models.Model):
    history_id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    Nama_field = models.CharField(max_length=15)
    field_awal = models.CharField(max_length=50)
    field_update = models.CharField(max_length=50)
    record_Del = models.CharField(max_length=255)
    TGL_UPDT = models.CharField(max_length=8)
    JM_UPDT = models.CharField(max_length=6)
    TGL_APPRV_UPDATE = models.CharField(max_length=8)
    JM_APPRV_UPDT = models.CharField(max_length=6)
    USR_UPDT = models.CharField(max_length=15)
    APPRV_UPDT = models.CharField(max_length=15)
    TGL_DELETE = models.CharField(max_length=8)
    JM_DELETE = models.CharField(max_length=6)
    TGL_APPRV_DELETE = models.CharField(max_length=8)
    JM_APPRV_DELETE = models.CharField(max_length=6)
    USR_Delete = models.CharField(max_length=15)
    APPRV_DELETE = models.CharField(max_length=15)

class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, phone_number, address, agency, password=None):
        if not email:
            raise ValueError('Email harus diisi.')
        email = self.normalize_email(email)
        user = self.model(
            username=username,
            email=email,
            phone_number=phone_number,
            address=address,
            agency=agency,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, phone_number, address, agency, password):
        user = self.create_user(
            username=username,
            email=email,
            phone_number=phone_number,
            address=address,
            agency=agency,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=17)
    address = models.CharField(max_length=255)
    agency = models.CharField(max_length=255)
    profile_photo = models.ImageField(upload_to='images/')
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'phone_number', 'address', 'agency']

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

myproject/bankapp/forms.py
from django import forms
from .models import CustomUser, Customer, Transaction, User
from django.forms.widgets import DateInput
from django.contrib.auth.forms import AuthenticationForm

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['account_id', 'name']

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['account', 'transaction_date', 'description', 'debit_credit_status', 'amount']
        widgets = {
            'transaction_date': DateInput(attrs={'type': 'date'}),
        }

class CustomUserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['username', 'password']

class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Konfirmasi Password', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'phone_number', 'address', 'agency')

    def clean_password2(self):
        # Periksa apakah kedua kata sandi yang dimasukkan cocok
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Kata sandi tidak cocok')
        return password2

    def save(self, commit=True):
        # Simpan pengguna dengan kata sandi yang dienkripsi
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
    
class ExcelUploadForm(forms.Form):
    excel_file = forms.FileField(label='Pilih file Excel')    

myproject/bankapp/views.py
from django.shortcuts import render, redirect
from .models import Customer, Transaction, Point, CustomerVico
from .forms import CustomerForm, TransactionForm, CustomUserLoginForm, RegistrationForm, ExcelUploadForm
from django.template import loader
from django.http import HttpResponse
from django.db.models import Sum, F, FloatField, ExpressionWrapper
from decimal import Decimal
from django.shortcuts import get_object_or_404
import datetime
from django.contrib.auth import authenticate, login
from django.contrib import messages
import pandas as pd

def input_customer(request):
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('customer_list')
    else:
        form = CustomerForm()
    return render(request, 'banking/input_customer.html', {'form': form})

def customer_list(request):
    customers = Customer.objects.all()
    return render(request, 'banking/customer_list.html', {'customers': customers})

def calculate_points(amount,transaction_type, transaction_desc,account_id):
    point, created = Point.objects.get_or_create(account_id=account_id)
    if point :
        if transaction_type == 'C':
            if transaction_desc == 'Beli Pulsa':
                if amount <= 10000:
                    point.total_point += 0
                elif 10000 < amount <= 30000:
                    point_awal = point.total_point
                    hitungan= (amount - 10000) / 1000
                    point.total_point = point_awal + hitungan
                else:
                    point_awal = point.total_point
                    hitungan = (amount - 30000) / 1000
                    point_tambahan = (2 * hitungan) + 20
                    point.total_point = point_awal +  point_tambahan
            elif transaction_desc == 'Bayar Listrik':
                if amount <= 50000:
                    point.total_point += 0
                elif 50000 < amount <= 100000:
                    point_awal = point.total_point
                    hitungan= (amount - 50000) / 2000
                    point.total_point = point_awal + hitungan
                else:
                    point_awal = point.total_point
                    hitungan = (amount - 100000) / 2000
                    point_tambahan = (2 * hitungan) + 25
                    point.total_point = point_awal +  point_tambahan
            point.save()

def input_transaction(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            form.save()
            amount = form.cleaned_data['amount']
            transaction_type = form.cleaned_data['debit_credit_status']
            transaction_desc = form.cleaned_data['description']
            account = form.cleaned_data['account']
            customer = get_object_or_404(Customer, name=account)
            calculate_points(amount, transaction_type, transaction_desc, customer.id)
            return redirect('transaction_list')
    else:
        form = TransactionForm()
    return render(request, 'banking/input_transaction.html', {'form': form})

def transaction_list(request):
    transactions = Transaction.objects.all()
    return render(request, 'banking/transaction_list.html', {'transactions': transactions})

def main(request):
    year = datetime.datetime.now().year
    return render(request, 'base.html', {'year': year})

def point_list(request):
    points = Point.objects.all()
    return render(request, 'banking/point_list.html', {'points': points})

def report_buku_tabungan(request):
    if request.method == 'POST':
        account_id = request.POST.get('account_id')
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        customer = get_object_or_404(Customer, account_id=account_id)

        transactions = Transaction.objects.filter(
            account_id = customer,
            transaction_date__range=[start_date, end_date]
        )

        balance = Decimal(0)
        for transaction in transactions:
            if transaction.debit_credit_status == 'C':
                balance -= transaction.amount
            else:
                balance += transaction.amount

            transaction.balance = balance

        return render(request, 'banking/report_buku_tabungan.html', {'transactions': transactions})
    else:
        return render(request, 'banking/input_report.html')

def user_login(request):
    if request.method == 'POST':
        form = CustomUserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Redirect ke halaman setelah login sukses
                return redirect('customer_list')
            else:
                # Username atau password salah, tambahkan pesan kesalahan
                messages.error(request, 'Username atau password salah. Silakan coba lagi.')
        else:
            # Form tidak valid, tambahkan pesan kesalahan
            messages.error(request, 'Form login tidak valid. Silakan coba lagi.')
    else:
        form = CustomUserLoginForm()
    return render(request, 'banking/login.html', {'form': form})

def user_registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('customer_list')
    else:
        form = RegistrationForm()
    return render(request, 'banking/registration.html', {'form': form})

def upload_excel(request):
    if request.method == 'POST':
        form = ExcelUploadForm(request.POST, request.FILES)
        if form.is_valid():
            excel_file = request.FILES['excel_file']
            if excel_file.name.endswith('.xlsx'):
                df = pd.read_excel(excel_file)
                for _, row in df.iterrows():
                    CustomerVico.objects.create(
                        NAMA_NASABAH=row['Customer Name'],
                        ACCTNO=row['Nomor Rekening '],
                        NO_IDEN=row['Nomor Identitas']
                    )
                return redirect('customer_list')  # Ganti 'success_page' dengan halaman sukses Anda
            else:
                form.add_error('excel_file', 'Harap unggah file Excel dengan format .xlsx')
    else:
        form = ExcelUploadForm()
    return render(request, 'banking/upload_excel.html', {'form': form})

myproject/bankapp/templates/banking/customer_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Daftar Nasabah</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Account ID</th>
        <th>Nama</th>
      </tr>
    </thead>
    <tbody>
      {% for customer in customers %}
      <tr>
        <td>{{ customer.account_id }}</td>
        <td>{{ customer.name }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="2">Belum ada nasabah.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'input_customer' %}" class="btn btn-primary">Input Data Nasabah</a>
{% endblock %}

myproject/bankapp/templates/banking/input_customer.html
{% extends 'base.html' %}

{% block content %}
  <h2>Input Data Nasabah</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Simpan</button>
  </form>
  <br>
  <a href="{% url 'customer_list' %}" class="btn btn-secondary">Lihat Daftar Nasabah</a>
{% endblock %}

myproject/bankapp/templates/banking/input_report.html
{% extends 'base.html' %}

{% block content %}
  <h2>Cetak Buku Tabungan</h2>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="account_id">Account ID:</label>
      <input type="text" class="form-control" id="account_id" name="account_id" required>
    </div>
    <div class="form-group">
      <label for="start_date">Start Date:</label>
      <input type="date" class="form-control" id="start_date" name="start_date" required>
    </div>
    <div class="form-group">
      <label for="end_date">End Date:</label>
      <input type="date" class="form-control" id="end_date" name="end_date" required>
    </div>
    <button type="submit" class="btn btn-primary">Cetak</button>
  </form>
{% endblock %}

myproject/bankapp/templates/banking/input_transaction.html
{% extends 'base.html' %}

{% block content %}
  <h2>Input Transaksi</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Simpan</button>
  </form>
  <br>
  <a href="{% url 'transaction_list' %}" class="btn btn-secondary">Lihat Daftar Transaksi</a>
{% endblock %}

myproject/bankapp/templates/banking/login.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>

myproject/bankapp/templates/banking/point_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Point Nasabah</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Account ID</th>
        <th>Nama</th>
        <th>Total Point</th>
      </tr>
    </thead>
    <tbody>
      {% for point in points %}
      <tr>
        <td>{{ point.account.account_id }}</td>
        <td>{{ point.account.name }}</td>
        <td>{{ point.total_point }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="3">Belum ada poin.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

myproject/bankapp/templates/banking/registration.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>

myproject/bankapp/templates/banking/report_buku_tabungan.html
{% extends 'base.html' %}

{% block content %}
  <h2>Laporan Buku Tabungan</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Tanggal Transaksi</th>
        <th>Deskripsi</th>
        <th>Credit</th>
        <th>Debit</th>
        <th>Saldo</th>
      </tr>
    </thead>
    <tbody>
      {% if transactions %}
        {% with saldo=0 %}
          {% for transaction in transactions %}
          <tr>
            <td>{{ transaction.transaction_date }}</td>
            <td>{{ transaction.description }}</td>
            <td>
              {% if transaction.debit_credit_status == 'C' %}
                {{ transaction.amount }}
              {% endif %}
            </td>
            <td>
              {% if transaction.debit_credit_status == 'D' %}
                {{ transaction.amount }}
              {% endif %}
            </td>
            <td>
                {{ transaction.balance }}
            </td>
            {% if transaction.debit_credit_status == 'C' %}
              {% with saldo=saldo|add:transaction.amount %}
              {% endwith %}
            {% endif %}
          </tr>
          {% endfor %}
        {% endwith %}
      {% else %}
        <tr>
          <td colspan="5">Tidak ada transaksi dalam rentang tanggal yang dipilih.</td>
        </tr>
      {% endif %}
    </tbody>
  </table>
{% endblock %}

myproject/bankapp/templates/banking/transaction_list.html
{% extends 'base.html' %}

{% block content %}
  <h2>Daftar Transaksi</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Account ID</th>
        <th>Tanggal Transaksi</th>
        <th>Deskripsi</th>
        <th>Debit/Credit</th>
        <th>Nominal</th>
      </tr>
    </thead>
    <tbody>
      {% for transaction in transactions %}
      <tr>
        <td>{{ transaction.account.account_id }}</td>
        <td>{{ transaction.transaction_date }}</td>
        <td>{{ transaction.description }}</td>
        <td>{{ transaction.get_debit_credit_status_display }}</td>
        <td>Rp {{ transaction.amount|floatformat:2 }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="5">Belum ada transaksi.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'input_transaction' %}" class="btn btn-primary">Input Transaksi</a>
{% endblock %}

myproject/bankapp/templates/banking/upload_excel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload Excel</title>
</head>
<body>
    <h1>Upload Excel Data</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Upload">
    </form>
</body>
</html>